#-------------[ ABOUT ]-------------
#
# Config file with settings for the E. faecium nanopore project
#
# To adapt to your project change the files and settings below
# The paths are relative to the root of the repository
#
# The script running on the HPC uses a separate config file: scripts/HPC/HPC_config.py
#
#------------------------------------


# --- Inputs ---
# Change this to your nanodrop data if you are using something else
raw_fastq_path: "data/raw/CCUG-33829.fastq.gz"
# MultiQC report paths
multiqc_input_path: "results/"
# Bakta database path
bakta_db_path: "data/bakta_database/"
# Bakta input genome path
flye_assembly_path: "data/processed/assembly.fasta"

# --- Outputs ---
# Output paths for multiQC reports
multiqc_output_path: "results/multiqc_reports/"
# Fastplong report paths
fastplong_output_path: "results/fastplong_output/"
# Bakta output path
bakta_output_path: "results/bakta_output/"
# AMRFinderPlus output path
amrfinder_output_file: "results/amrfinder.tsv" 
# MLST output path
mlst_output_file: "results/mlst.txt"


# --- Processed data ---
fastplong_filtered_path: "data/processed/CCUG-33829.filtered.fastq.gz"
medaka_polished_path: "data/processed/CCUG-33829.medaka.fasta"
