name: efaecium_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - about-time=4.2.1=pyhd8ed1ab_1
  - alive-progress=3.0.1=pyhd8ed1ab_0
  - alsa-lib=1.2.11=hd590300_1
  - anndata=0.10.9=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - any2fasta=0.4.2=hdfd78af_3
  - aragorn=1.2.41=h7b50bb2_5
  - archspec=0.2.5=pyhd8ed1ab_0
  - argtable2=2.13=hd590300_1004
  - array-api-compat=1.11.2=pyh29332c3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - bakta=1.3.1=pyhdfd78af_0
  - biopython=1.85=py39h8cd3c5a_1
  - blast=2.15.0=pl5321h6f7f691_1
  - blast-legacy=2.2.26=h9ee0642_4
  - brotli=1.1.0=hb9d3cd8_3
  - brotli-bin=1.1.0=hb9d3cd8_3
  - brotli-python=1.1.0=py39hf88036b_3
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=h3faef2a_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py39h15c3d72_0
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - clustalo=1.2.4=h503566f_10
  - clustalw=2.1=h9948957_12
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - colormath=3.0.0=pyhd8ed1ab_4
  - comm=0.2.3=pyhe01879c_0
  - consan=1.2=h7b50bb2_7
  - contourpy=1.3.0=py39h74842e3_2
  - cpython=3.9.23=py39hd8ed1ab_0
  - curl=8.8.0=he654da7_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py39haef64b4_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dendropy=5.0.8=pyhdfd78af_1
  - dialign-tx=1.0.2=h7b50bb2_8
  - diamond=2.1.10=h43eeafb_2
  - dnspython=2.7.0=pyhff2d567_1
  - entrez-direct=24.0=he881be0_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - famsa=2.2.3=h9948957_1
  - fastplong=0.2.1=h125f33a_0
  - fasttree=2.2.0=h7b50bb2_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.1=py39heb7d2ae_0
  - freetype=2.12.1=h267a509_2
  - gawk=5.3.1=hcd3d067_0
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - gmp=6.3.0=hac33072_2
  - grapheme=0.6.0=pyhd8ed1ab_1
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py39h30a5a8d_100
  - harfbuzz=9.0.0=hfac3d4d_0
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - hmmer=3.4=hb6cb901_4
  - hpack=4.1.0=pyhd8ed1ab_0
  - humanfriendly=10.0=pyh707e725_8
  - humanize=4.12.3=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - infernal=1.1.5=pl5321h7b50bb2_4
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.18.1=pyh707e725_3
  - isa-l=2.31.1=hb9d3cd8_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - kaleido-core=0.2.1=h3644ca4_0
  - kalign2=2.04=h7b50bb2_8
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - legacy-api-wrap=1.4=pyhd8ed1ab_1
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.4=h3f801dc_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libblas=3.9.0=37_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=37_h0358290_openblas
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.8.0=hca28451_1
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libglib=2.80.2=hf974151_0
  - libgomp=15.2.0=h767d61c_7
  - libhwloc=2.11.2=default_he43201b_1000
  - libhwy=1.1.0=h00ab1b0_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=hfac485b_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=37_h47877c9_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=hc051c1a_1
  - libzlib=1.2.13=h4ab18f5_6
  - llvmlite=0.42.0=py39h174d805_1
  - longqc=1.2.0c=hdfd78af_0
  - mafft=7.526=h4bc722e_0
  - markdown=3.8.2=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py39h9399b63_1
  - mathjax=2.7.7=ha770c72_3
  - matplotlib-base=3.9.4=py39h16632d1_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - minimap2-coverage=1.2.0c=he4a0461_3
  - mlst=2.23.0=hdfd78af_1
  - mpfr=4.2.1=h90cbb55_3
  - mpi=1.0=openmpi
  - multiqc=1.31=pyhdfd78af_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - muscle=3.8.1551=h9948957_9
  - mustang=3.2.4=h9948957_0
  - narwhals=2.1.2=pyhe01879c_0
  - natsort=8.4.0=pyh29332c3_1
  - ncbi-amrfinderplus=3.12.8=h283d18e_0
  - ncbi-vdb=3.2.1=h9948957_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - nspr=4.37=h29cc59b_0
  - nss=3.100=hca3bf56_0
  - numba=0.59.1=py39h615d6bd_0
  - numpy=1.26.4=py39h474f0d3_0
  - openjdk=22.0.1=hb622114_0
  - openjpeg=2.5.2=h488ebb8_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - paml=4.10.9=h7b50bb2_1
  - pandas=2.3.1=py39h1b6b32d_0
  - parallel=20250822=ha770c72_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pasta=1.9.2=py39h640ec12_5
  - patsy=1.0.1=pyhd8ed1ab_1
  - pbzip2=1.1.13=h1fcc475_2
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-algorithm-diff=1.201=pl5321hd8ed1ab_0
  - perl-archive-tar=3.04=pl5321hdfd78af_0
  - perl-b-cow=0.007=pl5321hb9d3cd8_1
  - perl-base=2.23=pl5321hd8ed1ab_0
  - perl-bio-asn1-entrezgene=1.73=pl5321hdfd78af_3
  - perl-bio-coordinate=1.007001=pl5321hdfd78af_3
  - perl-bio-featureio=1.6.905=pl5321hdfd78af_4
  - perl-bio-samtools=1.43=pl5321he4a0461_4
  - perl-bio-searchio-hmmer=1.7.3=pl5321hdfd78af_0
  - perl-bio-tools-phylo-paml=1.7.3=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl5321hdfd78af_3
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl5321hdfd78af_5
  - perl-bioperl=1.7.8=hdfd78af_1
  - perl-bioperl-core=1.7.8=pl5321hdfd78af_1
  - perl-bioperl-run=1.007003=pl5321hdfd78af_0
  - perl-business-isbn=3.007=pl5321hd8ed1ab_0
  - perl-business-isbn-data=20210112.006=pl5321hd8ed1ab_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-class-data-inheritable=0.09=pl5321ha770c72_0
  - perl-class-method-modifiers=2.13=pl5321ha770c72_0
  - perl-clone=0.46=pl5321hb9d3cd8_1
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.213=pl5321hda65f42_0
  - perl-compress-raw-zlib=2.213=pl5321h4dac143_0
  - perl-constant=1.33=pl5321hd8ed1ab_0
  - perl-data-dump=1.25=pl5321h7b50bb2_2
  - perl-data-dumper=2.183=pl5321hb9d3cd8_1
  - perl-db_file=1.858=pl5321hb9d3cd8_0
  - perl-devel-stacktrace=2.04=pl5321h296ab09_0
  - perl-digest-hmac=1.05=pl5321hdfd78af_0
  - perl-digest-md5=2.59=pl5321hb9d3cd8_3
  - perl-encode=3.21=pl5321hb9d3cd8_1
  - perl-encode-locale=1.05=pl5321hdfd78af_7
  - perl-exception-class=1.45=pl5321ha770c72_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-file-listing=6.16=pl5321hdfd78af_0
  - perl-file-slurper=0.014=pl5321hdfd78af_0
  - perl-file-sort=1.01=pl5321hdfd78af_3
  - perl-file-spec=3.48_01=pl5321hdfd78af_2
  - perl-file-which=1.24=pl5321hd8ed1ab_0
  - perl-getopt-long=2.58=pl5321hdfd78af_0
  - perl-html-parser=3.81=pl5321h4ac6f70_1
  - perl-html-tagset=3.24=pl5321hdfd78af_0
  - perl-http-cookiejar-lwp=0.014=pl5321hdfd78af_0
  - perl-http-cookies=6.11=pl5321hdfd78af_0
  - perl-http-daemon=6.16=pl5321hdfd78af_0
  - perl-http-date=6.06=pl5321hdfd78af_0
  - perl-http-message=7.01=pl5321hdfd78af_0
  - perl-http-negotiate=6.01=pl5321hdfd78af_4
  - perl-inc-latest=0.500=pl5321ha770c72_0
  - perl-io-compress=2.213=pl5321h503566f_0
  - perl-io-html=1.004=pl5321hdfd78af_0
  - perl-io-socket-ssl=2.075=pl5321hd8ed1ab_0
  - perl-io-string=1.08=pl5321hdfd78af_4
  - perl-io-tty=1.20=pl5321hb9d3cd8_3
  - perl-io-zlib=1.15=pl5321hdfd78af_1
  - perl-ipc-run=20250809.0=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.04=pl5321h9948957_0
  - perl-libwww-perl=6.81=pl5321hdfd78af_0
  - perl-libxml-perl=0.08=pl5321hdfd78af_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h7b50bb2_5
  - perl-lwp-mediatypes=6.04=pl5321hdfd78af_1
  - perl-lwp-protocol-https=6.14=pl5321hdfd78af_1
  - perl-mime-base64=3.16=pl5321hb9d3cd8_3
  - perl-module-build=0.4234=pl5321ha770c72_1
  - perl-module-load=0.34=pl5321hdfd78af_0
  - perl-moo=2.005004=pl5321ha770c72_0
  - perl-mozilla-ca=20250602=pl5321hdfd78af_0
  - perl-net-http=6.24=pl5321hdfd78af_0
  - perl-net-ssleay=1.92=pl5321hf14f497_1
  - perl-ntlm=1.09=pl5321hdfd78af_5
  - perl-parent=0.243=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321hb9d3cd8_2
  - perl-role-tiny=2.002004=pl5321ha770c72_0
  - perl-scalar-list-utils=1.70=pl5321hb03c661_0
  - perl-socket=2.027=pl5321h5c03b87_6
  - perl-storable=3.15=pl5321hb9d3cd8_2
  - perl-sub-quote=2.006006=pl5321ha770c72_0
  - perl-sub-uplevel=0.2800=pl5321hb9d3cd8_0
  - perl-test-deep=1.130=pl5321hd8ed1ab_0
  - perl-test-differences=0.72=pl5321ha770c72_0
  - perl-test-exception=0.43=pl5321hd8ed1ab_0
  - perl-test-fatal=0.016=pl5321ha770c72_0
  - perl-test-most=0.38=pl5321hdfd78af_0
  - perl-test-needs=0.002009=pl5321hd8ed1ab_0
  - perl-test-requiresinternet=0.05=pl5321hdfd78af_1
  - perl-test-warn=0.37=pl5321hd8ed1ab_0
  - perl-test-warnings=0.031=pl5321ha770c72_0
  - perl-text-diff=1.45=pl5321hd8ed1ab_0
  - perl-time-local=1.35=pl5321hdfd78af_0
  - perl-timedate=2.33=pl5321hdfd78af_2
  - perl-tree-dag_node=1.35=pl5321hdfd78af_0
  - perl-try-tiny=0.31=pl5321ha770c72_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - perl-uri=5.34=pl5321ha770c72_0
  - perl-url-encode=0.03=pl5321h9ee0642_1
  - perl-www-robotrules=6.02=pl5321hdfd78af_4
  - perl-xml-dom=1.46=pl5321hdfd78af_1
  - perl-xml-dom-xpath=0.14=pl5321hdfd78af_2
  - perl-xml-parser=2.44_01=pl5321hf2e2c51_1004
  - perl-xml-regexp=0.04=pl5321hdfd78af_3
  - perl-xml-xpathengine=0.14=pl5321hdfd78af_3
  - pexpect=4.9.0=pyhd8ed1ab_1
  - phylip=3.697=h7b50bb2_3
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pigz=2.8=h2797004_0
  - piler-cr=1.06=h9948957_6
  - pillow=10.3.0=py39h90c7501_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - platformdirs=4.3.8=pyhe01879c_0
  - plotly=6.3.0=pyhd8ed1ab_0
  - poa=2.0=h7b50bb2_6
  - polars-lts-cpu=1.33.1=py39h5734d0f_0
  - prank=170427=h9948957_1
  - probcons=1.12=h8b12597_1
  - probconsrna=1.10=h9f5acd7_4
  - proda=1.0=h503566f_7
  - prodigal=2.6.3=h7b50bb2_10
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39h8cd3c5a_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pyaml-env=1.2.2=pyhd8ed1ab_0
  - pycirclize=1.9.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-core=2.33.2=py39h20260ba_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyhmmer=0.11.1=py39hbcbf7aa_2
  - pymongo=4.13.2=py39h818bca1_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.3=pyhe01879c_2
  - pyrodigal=3.6.3.post1=py39hbcbf7aa_1
  - pysam=0.22.1=py39h61809e1_2
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.9.19=h0755675_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.1=pyhe01879c_0
  - python-edlib=1.3.9.post1=py39h2de1943_2
  - python-gil=3.9.23=hd8ed1ab_0
  - python-isal=1.7.2=py39h8cd3c5a_0
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python-zlib-ng=0.5.1=py39h1635d6b_0
  - python_abi=3.9=8_cp39
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py39h9399b63_2
  - pyzmq=27.0.2=py39haa5fa38_0
  - qhull=2020.2=h434a139_5
  - raxml=8.2.13=h7b50bb2_3
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - regex=2025.7.34=py39hd399759_0
  - requests=2.32.5=pyhd8ed1ab_0
  - rich=14.1.0=pyhe01879c_0
  - rich-click=1.8.9=pyhd8ed1ab_0
  - rpds-py=0.27.0=py39h17f49b6_0
  - sap=1.1.3=h7b50bb2_5
  - scanpy=1.10.3=pyhd8ed1ab_0
  - scikit-learn=1.6.1=py39h4b7350c_0
  - scipy=1.13.1=py39haf93ffa_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - spectra=0.0.11=pyhd8ed1ab_2
  - sqlite=3.46.0=h6d4b2fc_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py39h7c0b2d6_0
  - stdlib-list=0.11.1=pyhd8ed1ab_0
  - t-coffee=13.46.2.7c9e712d=pl5321hb2a3317_0
  - tbb=2022.1.0=h4ce085d_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tiktoken=0.11.0=py39h279891f_0
  - tk=8.6.13=noxft_h4845f30_101
  - tmalign=20170708=h8d36177_7
  - tornado=6.5.2=py39hd399759_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - trnascan-se=2.0.12=pl5321h7b50bb2_2
  - typeguard=4.4.4=pyhd8ed1ab_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.9.post2=py39hf3d152e_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - viennarna=2.7.0=py39pl5321hc9faaad_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wget=1.21.4=hda4d442_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xopen=2.0.2=pyh707e725_2
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstandard=0.23.0=py39hd399759_3
  - zstd=1.5.6=ha6fb4c9_0
prefix: /home/delusional/miniconda3/envs/efaecium_env
